### ISSUE TITLE
app crashing or closing itself

### ISSUE THREAD

**Issue by praramis** [Razzmatazzz/ValheimServerWarden#31] opened 2021-03-12 06:52 UTC
ok so im not sure what is causing it yet as when it happens it saves no logs what so ever but the app 4.14 was running fine and earlier today i realized the discord notifications stopped so i went to look and the app had closed itself somehow but the server was still running so i tried to relaunch app and says servers running would you like to shut down and use this app and i hit yes and just restart the process  and this just keeps happening over and over i have no idea how to help debug this info so if you know any tricks or ways to figure out why its self closing please let me know so i can help

**Comment by Razzmatazzz** [comment] 2021-03-12 13:30
To help us narrow down the cause of the crash:

- Do you have an idea how long the server runs before VSW crashes?
- Is the last Discord notification message always the same?
- Have you enabled the "Create log file" option in the main VSW app settings?

**Comment by Razzmatazzz** [comment] 2021-03-16 02:50
@praramis Please let me know the answer to the above questions when you have a moment. It's nigh impossible for me to track down bugs when I'm not experiencing them myself.

**Comment by Razzmatazzz** [comment] 2021-03-20 03:04
@praramis Are you still experiencing this issue? I have not been able to replicate it.

**Comment by Razzmatazzz** [comment] 2021-03-22 17:03
I'm closing this issue since I haven't received any additional information for over a week. If you can provide some additional details, we can reopen the issue.

**Comment by necromancyr** [comment] 2021-04-05 23:33
This is 100% happening.  Just confirmed it a few times - ran fine from 10am until 6:51pm at least - then nothing.  Not certain what the deal is.  The server itself is still running and I can see it on Steam, but VSW isn't and the server is still running w/o a shell window.  

It's more problematic because you can't just restart VSW than anything else.  

I have a log file being generated and it looks like it's just status messages and then it stops - last message on mine was just someone leaving the server.

**Comment by Razzmatazzz** [comment] 2021-04-05 23:52
To get VSW running again, just re-launch the app and it should ask if you want to shut down running servers (assuming you have that option enabled in VSW), just click yes and then re-start the server via VSW.

It seems like this issue is intermittent, which makes narrowing down the cause rather challenging. To help narrow down the potential causes, can you provide some information about your settings? E.g., whether you have the server set to auto-restart on a schedule, whether you have it set to check for updates automatically, etc.

**Comment by necromancyr** [comment] 2021-04-06 00:09
So, settings are:
- Public Server
- No save folder set (just defaulting)
- - Logging raw server output to file
- Restarting every 4 hours
- Updating on restart
- Check for and apply available updates every 20 minutes
- SteamCMD install type

And the problem with restarting is it kicks anyone on at the time and potentially causes data to be lost in the game.

The above is basically default also - aside from turning things on, I didn't really change settings re: restart time, etc., as I figured that was an optimal window since it was default (the 4 hours restart and 20 minutes check).

**Comment by doublee313** [comment] 2021-04-06 00:51
I also noticed tbis

Sent from Samsung Galaxy S9+

________________________________

**Comment by Razzmatazzz** [comment] 2021-04-06 01:16
Yes, anyone on the server will be kicked if your select the option to stop running servers, but it doesn't just terminate the process. It sends the same exit signal to the running server as if you clicked "Stop" in VSW. That should cause it to shut down gracefully and save the world in the process.

My guess is the bug relates somehow to either discord webhooks or checking for updates not associated with a restart. If the app was crashing when it was restarting or checking for an update during the restart process, the server wouldn't get re-launched.

**Comment by necromancyr** [comment] 2021-04-06 13:46
Suggestions on best approach to debug/try to isolate?  Want to provide more details, but it's not clear where to poke/prod.

**Comment by Razzmatazzz** [comment] 2021-04-06 14:30
[vsw.zip](https://github.com/Razzmatazzz/ValheimServerWarden/files/6265356/vsw.zip)
This test build should hopefully be a bit more robust and display an error message rather than crash. If we can get an error message, that'll help narrow down where the problem is.

**Comment by necromancyr** [comment] 2021-04-06 17:16
Let's see how it goes...running now.  Where will the errors be captured - log file?

**Comment by Razzmatazzz** [comment] 2021-04-06 17:20
Errors should appear in the app log and/or the server log displayed in the app, depending on where they're generated.

**Comment by necromancyr** [comment] 2021-04-06 23:57
First error.  Been up for about 6 hours, people logging on and off and all seems good.   Someone logged on about an hour before this, logged off about 15 minutes after.  Server's still up and ok it seems.  VSW still up and fine as well.

4/6/2021 7:01:46 PM: Error parsing update check output: StartIndex cannot be less than zero. (Parameter 'startIndex')

**Comment by Razzmatazzz** [comment] 2021-04-07 02:21
Sounds like SteamCMD is providing unexpected output sometimes when checking for an update. Makes sense that intermittent network issues could throw a wrench in that process. Thanks for testing.

**Comment by Razzmatazzz** [comment] 2021-04-07 12:30
The 0.4.18.0 release should stop these crashes. I'll leave this issue open for a bit in case anyone continues to experience them.

**Comment by necromancyr** [comment] 2021-04-08 17:09
I'm continuing to run the error tracking version and the error I posted above is the only thing I'm seeing so far.  VSW hasn't crashed out once as of yet, and it's been going >24 hours.  I'll keep it going and see. 

Just curious, but is the error tracking version capturing things differently than 0.4.17 was?  I expected VSW to crash out again and then have to look in the log for the error vs. what seems to be happening now is the reason I ask.

**Comment by Razzmatazzz** [comment] 2021-04-08 17:25
I wouldn't expect it to crash; it should just display an error instead. If I can get it to display an error gracefully, there's no reason to let it crash.

**Comment by necromancyr** [comment] 2021-04-09 15:13
So...had a crash.  The server totally died - and VSW went down with it.  Not sure if this is expected behavior or not - my expectation would be that VSW detects it and relaunches the server.  (Note, I'm still running the error tracking version above.)

4/8/2021 10:55:00 PM: XXXXXXXX: Server exited with code 1073807364.
4/8/2021 10:55:00 PM: XXXXXXXX: Server stopped unexpectedly.

**Comment by Razzmatazzz** [comment] 2021-04-09 15:46
[vsw.zip](https://github.com/Razzmatazzz/ValheimServerWarden/files/6286993/vsw.zip)
Currently, if the server is set to autostart, it should restart automatically after a crash. I might change it to restart any running server automatically after a crash. But either way, a crashing server shouldn't crash the whole app.

Do you have the raw server output log by chance?

Edit: The attached test version should provide some extra protections related to crashes stemming from the server process. It also automatically restarts any "crashed" server regardless of if the autostart setting is enabled.

**Comment by necromancyr** [comment] 2021-04-09 21:43
Got it - I didn't have autostart on. Also, just had a crash of VSW, server is still up - nothing in the VSW log.  (Just people joining & leaving.)

Will update to the version above and keep updating.

**Comment by Razzmatazzz** [comment] 2021-04-13 16:36
Has anyone continued experiencing crashes with the latest version? If not, I'd like to close this issue.

**Comment by necromancyr** [comment] 2021-04-13 23:37
Appears to be good to me - I can update to the newest version and continue to watch, but seems to be addressed as of now.

And thanks!

**Closed as completed** 2021-04-15 21:18 UTC
